server:
  port: 8086

spring:
  mvc:
    async:
      request-timeout: 15m
  application:
    name: incident
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/incident}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
grpc:
  server:
    port: 9091

incident:
  generator:
    url: ${OLLAMA_CHAT_URL:http://100.85.141.32:11434/api/chat}
    model: ${OLLAMA_MODEL:qwen3:4b-instruct-2507-q4_K_M}

classifier:
  grpc:
    host: ${CLASSIFIER_GRPC_HOST:localhost}
    port: ${CLASSIFIER_GRPC_PORT:9093}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
