server:
  port: 8086

spring:
  application:
    name: incident
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/incident}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
grpc:
  server:
    port: 9091
    
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
