# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc.com.simulator112.context import context_service_pb2 as com_dot_simulator112_dot_context_dot_context__service__pb2
from app.grpc.com.simulator112.incident import incident_context_pb2 as com_dot_simulator112_dot_incident_dot_incident__context__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in com/simulator112/context/context_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ContextManagerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIncidentContext = channel.unary_unary(
                '/context.ContextManagerService/GetIncidentContext',
                request_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.GetIncidentContextRequest.SerializeToString,
                response_deserializer=com_dot_simulator112_dot_incident_dot_incident__context__pb2.IncidentContext.FromString,
                _registered_method=True)
        self.AppendDialogContext = channel.unary_unary(
                '/context.ContextManagerService/AppendDialogContext',
                request_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.AppendDialogContextRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.AppendSolutionContext = channel.unary_unary(
                '/context.ContextManagerService/AppendSolutionContext',
                request_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.AppendSolutionContextRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetFullContext = channel.unary_unary(
                '/context.ContextManagerService/GetFullContext',
                request_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.GetFullContextRequest.SerializeToString,
                response_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.FullContext.FromString,
                _registered_method=True)
        self.GetNextDialup = channel.unary_unary(
                '/context.ContextManagerService/GetNextDialup',
                request_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.GetNextDialupRequest.SerializeToString,
                response_deserializer=com_dot_simulator112_dot_incident_dot_incident__context__pb2.DialupContext.FromString,
                _registered_method=True)
        self.GetDialup = channel.unary_unary(
                '/context.ContextManagerService/GetDialup',
                request_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.GetDialupRequest.SerializeToString,
                response_deserializer=com_dot_simulator112_dot_incident_dot_incident__context__pb2.DialupContext.FromString,
                _registered_method=True)
        self.GetDialogProgress = channel.unary_unary(
                '/context.ContextManagerService/GetDialogProgress',
                request_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.GetDialogProgressRequest.SerializeToString,
                response_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.DialogProgress.FromString,
                _registered_method=True)
        self.StartDialup = channel.unary_unary(
                '/context.ContextManagerService/StartDialup',
                request_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.StartDialupRequest.SerializeToString,
                response_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.DialogProgress.FromString,
                _registered_method=True)
        self.CompleteDialup = channel.unary_unary(
                '/context.ContextManagerService/CompleteDialup',
                request_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.CompleteDialupRequest.SerializeToString,
                response_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.DialogProgress.FromString,
                _registered_method=True)
        self.DisconnectDialup = channel.unary_unary(
                '/context.ContextManagerService/DisconnectDialup',
                request_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.DisconnectDialupRequest.SerializeToString,
                response_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.DialogProgress.FromString,
                _registered_method=True)


class ContextManagerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetIncidentContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendDialogContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendSolutionContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFullContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNextDialup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDialup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDialogProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartDialup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteDialup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisconnectDialup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContextManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIncidentContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIncidentContext,
                    request_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.GetIncidentContextRequest.FromString,
                    response_serializer=com_dot_simulator112_dot_incident_dot_incident__context__pb2.IncidentContext.SerializeToString,
            ),
            'AppendDialogContext': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendDialogContext,
                    request_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.AppendDialogContextRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AppendSolutionContext': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendSolutionContext,
                    request_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.AppendSolutionContextRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetFullContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFullContext,
                    request_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.GetFullContextRequest.FromString,
                    response_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.FullContext.SerializeToString,
            ),
            'GetNextDialup': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextDialup,
                    request_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.GetNextDialupRequest.FromString,
                    response_serializer=com_dot_simulator112_dot_incident_dot_incident__context__pb2.DialupContext.SerializeToString,
            ),
            'GetDialup': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDialup,
                    request_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.GetDialupRequest.FromString,
                    response_serializer=com_dot_simulator112_dot_incident_dot_incident__context__pb2.DialupContext.SerializeToString,
            ),
            'GetDialogProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDialogProgress,
                    request_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.GetDialogProgressRequest.FromString,
                    response_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.DialogProgress.SerializeToString,
            ),
            'StartDialup': grpc.unary_unary_rpc_method_handler(
                    servicer.StartDialup,
                    request_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.StartDialupRequest.FromString,
                    response_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.DialogProgress.SerializeToString,
            ),
            'CompleteDialup': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteDialup,
                    request_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.CompleteDialupRequest.FromString,
                    response_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.DialogProgress.SerializeToString,
            ),
            'DisconnectDialup': grpc.unary_unary_rpc_method_handler(
                    servicer.DisconnectDialup,
                    request_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.DisconnectDialupRequest.FromString,
                    response_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.DialogProgress.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'context.ContextManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('context.ContextManagerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ContextManagerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetIncidentContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/context.ContextManagerService/GetIncidentContext',
            com_dot_simulator112_dot_context_dot_context__service__pb2.GetIncidentContextRequest.SerializeToString,
            com_dot_simulator112_dot_incident_dot_incident__context__pb2.IncidentContext.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendDialogContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/context.ContextManagerService/AppendDialogContext',
            com_dot_simulator112_dot_context_dot_context__service__pb2.AppendDialogContextRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendSolutionContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/context.ContextManagerService/AppendSolutionContext',
            com_dot_simulator112_dot_context_dot_context__service__pb2.AppendSolutionContextRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFullContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/context.ContextManagerService/GetFullContext',
            com_dot_simulator112_dot_context_dot_context__service__pb2.GetFullContextRequest.SerializeToString,
            com_dot_simulator112_dot_context_dot_context__service__pb2.FullContext.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNextDialup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/context.ContextManagerService/GetNextDialup',
            com_dot_simulator112_dot_context_dot_context__service__pb2.GetNextDialupRequest.SerializeToString,
            com_dot_simulator112_dot_incident_dot_incident__context__pb2.DialupContext.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDialup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/context.ContextManagerService/GetDialup',
            com_dot_simulator112_dot_context_dot_context__service__pb2.GetDialupRequest.SerializeToString,
            com_dot_simulator112_dot_incident_dot_incident__context__pb2.DialupContext.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDialogProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/context.ContextManagerService/GetDialogProgress',
            com_dot_simulator112_dot_context_dot_context__service__pb2.GetDialogProgressRequest.SerializeToString,
            com_dot_simulator112_dot_context_dot_context__service__pb2.DialogProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartDialup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/context.ContextManagerService/StartDialup',
            com_dot_simulator112_dot_context_dot_context__service__pb2.StartDialupRequest.SerializeToString,
            com_dot_simulator112_dot_context_dot_context__service__pb2.DialogProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteDialup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/context.ContextManagerService/CompleteDialup',
            com_dot_simulator112_dot_context_dot_context__service__pb2.CompleteDialupRequest.SerializeToString,
            com_dot_simulator112_dot_context_dot_context__service__pb2.DialogProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisconnectDialup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/context.ContextManagerService/DisconnectDialup',
            com_dot_simulator112_dot_context_dot_context__service__pb2.DisconnectDialupRequest.SerializeToString,
            com_dot_simulator112_dot_context_dot_context__service__pb2.DialogProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
