# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc.com.simulator112.context import context_service_pb2 as com_dot_simulator112_dot_context_dot_context__service__pb2
from app.grpc.com.simulator112.incident import incident_context_pb2 as com_dot_simulator112_dot_incident_dot_incident__context__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in com/simulator112/context/context_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ContextManagerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIncidentContext = channel.unary_unary(
                '/context.ContextManagerService/GetIncidentContext',
                request_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.GetIncidentContextRequest.SerializeToString,
                response_deserializer=com_dot_simulator112_dot_incident_dot_incident__context__pb2.IncidentContext.FromString,
                _registered_method=True)
        self.AppendDialogContext = channel.unary_unary(
                '/context.ContextManagerService/AppendDialogContext',
                request_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.AppendDialogContextRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.AppendSolutionContext = channel.unary_unary(
                '/context.ContextManagerService/AppendSolutionContext',
                request_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.AppendSolutionContextRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetFullContext = channel.unary_unary(
                '/context.ContextManagerService/GetFullContext',
                request_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.GetFullContextRequest.SerializeToString,
                response_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.FullContext.FromString,
                _registered_method=True)
        self.GetNextCall = channel.unary_unary(
                '/context.ContextManagerService/GetNextCall',
                request_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.GetNextCallRequest.SerializeToString,
                response_deserializer=com_dot_simulator112_dot_incident_dot_incident__context__pb2.CallScenario.FromString,
                _registered_method=True)
        self.GetCall = channel.unary_unary(
                '/context.ContextManagerService/GetCall',
                request_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.GetCallRequest.SerializeToString,
                response_deserializer=com_dot_simulator112_dot_incident_dot_incident__context__pb2.CallScenario.FromString,
                _registered_method=True)
        self.GetDialogProgress = channel.unary_unary(
                '/context.ContextManagerService/GetDialogProgress',
                request_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.GetDialogProgressRequest.SerializeToString,
                response_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.DialogProgress.FromString,
                _registered_method=True)
        self.StartCall = channel.unary_unary(
                '/context.ContextManagerService/StartCall',
                request_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.StartCallRequest.SerializeToString,
                response_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.DialogProgress.FromString,
                _registered_method=True)
        self.CompleteCall = channel.unary_unary(
                '/context.ContextManagerService/CompleteCall',
                request_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.CompleteCallRequest.SerializeToString,
                response_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.DialogProgress.FromString,
                _registered_method=True)
        self.DisconnectCall = channel.unary_unary(
                '/context.ContextManagerService/DisconnectCall',
                request_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.DisconnectCallRequest.SerializeToString,
                response_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.DialogProgress.FromString,
                _registered_method=True)
        self.GetCallTranscript = channel.unary_unary(
                '/context.ContextManagerService/GetCallTranscript',
                request_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.GetCallTranscriptRequest.SerializeToString,
                response_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.DialogContext.FromString,
                _registered_method=True)
        self.ClearCallTranscript = channel.unary_unary(
                '/context.ContextManagerService/ClearCallTranscript',
                request_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.ClearCallTranscriptRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetLevelProgress = channel.unary_unary(
                '/context.ContextManagerService/GetLevelProgress',
                request_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.GetLevelProgressRequest.SerializeToString,
                response_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.LevelProgress.FromString,
                _registered_method=True)


class ContextManagerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetIncidentContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendDialogContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendSolutionContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFullContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNextCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDialogProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisconnectCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCallTranscript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearCallTranscript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLevelProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContextManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIncidentContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIncidentContext,
                    request_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.GetIncidentContextRequest.FromString,
                    response_serializer=com_dot_simulator112_dot_incident_dot_incident__context__pb2.IncidentContext.SerializeToString,
            ),
            'AppendDialogContext': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendDialogContext,
                    request_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.AppendDialogContextRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AppendSolutionContext': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendSolutionContext,
                    request_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.AppendSolutionContextRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetFullContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFullContext,
                    request_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.GetFullContextRequest.FromString,
                    response_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.FullContext.SerializeToString,
            ),
            'GetNextCall': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextCall,
                    request_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.GetNextCallRequest.FromString,
                    response_serializer=com_dot_simulator112_dot_incident_dot_incident__context__pb2.CallScenario.SerializeToString,
            ),
            'GetCall': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCall,
                    request_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.GetCallRequest.FromString,
                    response_serializer=com_dot_simulator112_dot_incident_dot_incident__context__pb2.CallScenario.SerializeToString,
            ),
            'GetDialogProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDialogProgress,
                    request_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.GetDialogProgressRequest.FromString,
                    response_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.DialogProgress.SerializeToString,
            ),
            'StartCall': grpc.unary_unary_rpc_method_handler(
                    servicer.StartCall,
                    request_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.StartCallRequest.FromString,
                    response_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.DialogProgress.SerializeToString,
            ),
            'CompleteCall': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteCall,
                    request_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.CompleteCallRequest.FromString,
                    response_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.DialogProgress.SerializeToString,
            ),
            'DisconnectCall': grpc.unary_unary_rpc_method_handler(
                    servicer.DisconnectCall,
                    request_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.DisconnectCallRequest.FromString,
                    response_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.DialogProgress.SerializeToString,
            ),
            'GetCallTranscript': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCallTranscript,
                    request_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.GetCallTranscriptRequest.FromString,
                    response_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.DialogContext.SerializeToString,
            ),
            'ClearCallTranscript': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearCallTranscript,
                    request_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.ClearCallTranscriptRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetLevelProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLevelProgress,
                    request_deserializer=com_dot_simulator112_dot_context_dot_context__service__pb2.GetLevelProgressRequest.FromString,
                    response_serializer=com_dot_simulator112_dot_context_dot_context__service__pb2.LevelProgress.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'context.ContextManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('context.ContextManagerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ContextManagerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetIncidentContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/context.ContextManagerService/GetIncidentContext',
            com_dot_simulator112_dot_context_dot_context__service__pb2.GetIncidentContextRequest.SerializeToString,
            com_dot_simulator112_dot_incident_dot_incident__context__pb2.IncidentContext.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendDialogContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/context.ContextManagerService/AppendDialogContext',
            com_dot_simulator112_dot_context_dot_context__service__pb2.AppendDialogContextRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendSolutionContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/context.ContextManagerService/AppendSolutionContext',
            com_dot_simulator112_dot_context_dot_context__service__pb2.AppendSolutionContextRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFullContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/context.ContextManagerService/GetFullContext',
            com_dot_simulator112_dot_context_dot_context__service__pb2.GetFullContextRequest.SerializeToString,
            com_dot_simulator112_dot_context_dot_context__service__pb2.FullContext.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNextCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/context.ContextManagerService/GetNextCall',
            com_dot_simulator112_dot_context_dot_context__service__pb2.GetNextCallRequest.SerializeToString,
            com_dot_simulator112_dot_incident_dot_incident__context__pb2.CallScenario.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/context.ContextManagerService/GetCall',
            com_dot_simulator112_dot_context_dot_context__service__pb2.GetCallRequest.SerializeToString,
            com_dot_simulator112_dot_incident_dot_incident__context__pb2.CallScenario.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDialogProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/context.ContextManagerService/GetDialogProgress',
            com_dot_simulator112_dot_context_dot_context__service__pb2.GetDialogProgressRequest.SerializeToString,
            com_dot_simulator112_dot_context_dot_context__service__pb2.DialogProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/context.ContextManagerService/StartCall',
            com_dot_simulator112_dot_context_dot_context__service__pb2.StartCallRequest.SerializeToString,
            com_dot_simulator112_dot_context_dot_context__service__pb2.DialogProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/context.ContextManagerService/CompleteCall',
            com_dot_simulator112_dot_context_dot_context__service__pb2.CompleteCallRequest.SerializeToString,
            com_dot_simulator112_dot_context_dot_context__service__pb2.DialogProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisconnectCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/context.ContextManagerService/DisconnectCall',
            com_dot_simulator112_dot_context_dot_context__service__pb2.DisconnectCallRequest.SerializeToString,
            com_dot_simulator112_dot_context_dot_context__service__pb2.DialogProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCallTranscript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/context.ContextManagerService/GetCallTranscript',
            com_dot_simulator112_dot_context_dot_context__service__pb2.GetCallTranscriptRequest.SerializeToString,
            com_dot_simulator112_dot_context_dot_context__service__pb2.DialogContext.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearCallTranscript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/context.ContextManagerService/ClearCallTranscript',
            com_dot_simulator112_dot_context_dot_context__service__pb2.ClearCallTranscriptRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLevelProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/context.ContextManagerService/GetLevelProgress',
            com_dot_simulator112_dot_context_dot_context__service__pb2.GetLevelProgressRequest.SerializeToString,
            com_dot_simulator112_dot_context_dot_context__service__pb2.LevelProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
