from typing import Protocol


class CallRecorder(Protocol):
    def record_operator(self, pcm: bytes) -> None: ...
    def record_counterparty(self, pcm: bytes) -> None: ...
    def close(self) -> str | None: ...


class CallRecorderFactory(Protocol):
    def create(self, context_id: str, call_id: str) -> CallRecorder: ...
