from typing import Protocol

from app.domain.model import CallScenario, DialogProgress, DialogTranscript


class NoMoreCallsError(Exception):
    pass


class ContextPort(Protocol):
    def get_progress(self, context_id: str) -> DialogProgress: ...
    def get_next_call(self, context_id: str, current_call_id: str = "-1") -> CallScenario: ...
    def get_call(self, context_id: str, call_id: str) -> CallScenario: ...
    def start_call(self, context_id: str, call_id: str) -> DialogProgress: ...
    def complete_call(self, context_id: str, call_id: str) -> DialogProgress: ...
    def disconnect_call(self, context_id: str, call_id: str) -> DialogProgress: ...
    def append_transcript(self, context_id: str, transcript: DialogTranscript) -> None: ...
