syntax = "proto3";

package simulator112.review;

import "com/simulator112/context/context_service.proto";

option java_package = "com.simulator112.review.grpc.contract";
option java_multiple_files = true;

service ReviewService {
  rpc sendOnReview(SendOnReviewRequest) returns (ReviewStatusResponse);
  rpc GetAssignmentResults(GetAssignmentResultsRequest) returns (GetAssignmentResultsResponse);
}

message GetAssignmentResultsRequest {
  string user_id = 1;
  repeated string assignment_ids = 2;
}

message GetAssignmentResultsResponse {
  repeated AssignmentResult results = 1;
}

message AssignmentResult {
  string assignment_id = 1;
  int32 score = 2;
  int32 max_score = 3;
  optional int32 grade = 4;
}

message SendOnReviewRequest {
  context.FullContext context = 1;
}

message ReviewStatusResponse {
  ReviewStatus status = 1;
}


enum ReviewStatus {
  CREATED = 0;
  FILLED = 1;
  IN_REVIEW = 2;
  DIALOG = 3;
  DONE = 4;
}
