server:
  port: 8087
spring:
  application:
    name: notification-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/notification}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
        debug: ${MAIL_DEBUG:false}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        "[spring.deserializer.key.delegate.class]": org.apache.kafka.common.serialization.StringDeserializer
        "[spring.deserializer.value.delegate.class]": org.springframework.kafka.support.serializer.JsonDeserializer
        "[spring.json.trusted.packages]": "com.simulator112.notification.dto"
        "[spring.json.type.mapping]": "com.simulator112.auth.dto.event.PasswordResetRequestedEvent:com.simulator112.notification.dto.PasswordResetEvent,com.simulator112.auth.dto.event.EmailVerificationRequestedEvent:com.simulator112.notification.dto.EmailVerificationRequestedEvent,com.simulator112.auth.dto.event.UserCreatedEvent:com.simulator112.notification.dto.UserCreatedEvent,com.simulator112.review_service.adapter.out.messaging.dto.ReviewCommentCreatedEvent:com.simulator112.notification.dto.ReviewCommentCreatedEvent"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

notification:
  app-base-url: ${APP_BASE_URL:http://localhost:4321}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

logging:
  level:
    "[com.simulator112.notification]": INFO
    "[org.springframework.kafka]": WARN
    "[org.hibernate.SQL]": DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
