# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/simulator112/common/dds_service.proto
# Protobuf Python Version: 7.34.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    2,
    '',
    'com/simulator112/common/dds_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)com/simulator112/common/dds_service.proto\x12\x06\x63ommon*\xa4\x01\n\nDdsService\x12\x1b\n\x17\x44\x44S_SERVICE_UNSPECIFIED\x10\x00\x12\x14\n\x10\x44\x44S_SERVICE_FIRE\x10\x01\x12\x16\n\x12\x44\x44S_SERVICE_POLICE\x10\x02\x12\x19\n\x15\x44\x44S_SERVICE_AMBULANCE\x10\x03\x12\x13\n\x0f\x44\x44S_SERVICE_GAS\x10\x04\x12\x1b\n\x17\x44\x44S_SERVICE_ANTI_TERROR\x10\x05\x42)\n%com.simulator112.common.grpc.contractP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.simulator112.common.dds_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%com.simulator112.common.grpc.contractP\001'
  _globals['_DDSSERVICE']._serialized_start=54
  _globals['_DDSSERVICE']._serialized_end=218
# @@protoc_insertion_point(module_scope)
