ALTER TABLE reviews ADD COLUMN automatic_score INTEGER NOT NULL DEFAULT 0;
ALTER TABLE reviews ADD COLUMN final_score INTEGER;
ALTER TABLE reviews ADD COLUMN max_score INTEGER NOT NULL DEFAULT 0;
ALTER TABLE reviews ADD COLUMN duration_seconds BIGINT NOT NULL DEFAULT 0;
ALTER TABLE reviews ADD COLUMN time_limit_seconds BIGINT NOT NULL DEFAULT 30;
ALTER TABLE reviews ADD COLUMN overtime_seconds BIGINT NOT NULL DEFAULT 0;
ALTER TABLE reviews ADD COLUMN expert_id UUID;
ALTER TABLE reviews ADD COLUMN expert_comment TEXT;
ALTER TABLE reviews ADD COLUMN confirmed_at TIMESTAMP WITH TIME ZONE;
