syntax = "proto3";

package incident;

import "com/simulator112/classifier/classifier.proto";

option java_package = "com.simulator112.incident.grpc.contract";
option java_multiple_files = true;

message LevelContext {
  string id = 1;
  string title = 2;
  repeated IncidentContext incidents = 3;
  Difficulty difficulty = 4;
}

message IncidentContext {
  string id = 1;
  string title = 2;
  Address address = 3;
  DispatcherCriteria dispatcher_criteria = 4;
  repeated StageContext stages = 5;
}

message StageContext {
  string id = 1;
  string title = 2;
  int32 position = 3;
  repeated DialupContext dialups = 4;
  Applicant victim = 5;
  string description = 6;
  classifier.ClassifierEntry classifier_entry = 7;
}

message DialupContext {
  string id = 1;
  int32 position = 2;
  DialupDetails dialup_details = 3;
  Applicant applicant = 4;
  Applicant victim = 5;
}

message Address {
  string city = 1;
  string street = 2;
  string house = 3;
  string building = 4;
  string apartment = 5;
  int32 floor = 6;
}

message Applicant {
  string first_name = 1;
  string last_name = 2;
  string middle_name = 3;
  int32 age = 4;
  string phone = 5;
  EmotionalState emotional_state = 6;
  string contact_phone = 7;
  string address = 8;
  string additional_info = 9;
}

message DialupDetails {
  Gender gender = 1;
  repeated string known_facts = 2;
  repeated string hidden_facts = 3;
  string ai_context = 4;
  string emotional_state = 5;
}

message DispatcherCriteria {
  repeated string required_questions = 1;
  repeated string expected_actions = 2;
  repeated string critical_mistakes = 3;
}

enum Difficulty {
  EASY = 0;
  NORMAL = 1;
  HARD = 2;
}

enum EmotionalState {
  CALM = 0;
  WORRIED = 1;
  PANICKED = 2;
  AGGRESSIVE = 3;
  CONFUSED = 4;
}

enum Gender {
  MAN = 0;
  WOMEN = 1;
}
