syntax = "proto3";

package incident;


option java_package = "com.simulator112.incident.grpc.contract";
option java_multiple_files = true;

message IncidentContext {
  string id = 1;
  string title = 2;
  Address address = 3;
  Difficulty difficulty = 4;
  IncidentTargetType target_type = 5;
  repeated IncidentStage stages = 6;
  Criteria criteria = 7;
  optional PreparedCardTemplate prepared_card_template = 8;
  optional InitialAssignment initial_assignment = 9;
}

message IncidentStage {
  string id = 1;
  string title = 2;
  string description = 5;
  repeated CallScenario calls = 6;

  oneof details {
    System112StageDetails system_112 = 7;
    DdsStageDetails dds = 8;
  }
}

message System112StageDetails {
  repeated string classifier_codes = 1;
  int32 victim_count = 2;
  int32 position = 3;
}

message DdsStageDetails {
  DdsStageType type = 1;
  int32 time_limit_seconds = 2;
  string expected_comment = 3;
  IncidentStatus actual_status = 5;
}

message CallScenario {
  string id = 1;
  int32 position = 2;
  CallDirection direction = 3;
  CounterpartyType counterparty = 4;
  Person person = 5;
  Gender gender = 6;
  repeated string known_facts = 7;
  repeated string hidden_facts = 8;
  string ai_context = 9;
  string emotional_state = 10;
  string service_code = 11;
}

message PreparedCardTemplate {
  repeated string classifier_codes = 1;
  Person applicant = 2;
  int32 victim_count = 3;
  map<string, string> additional_info = 4;
}

message InitialAssignment {
  string emergency_service_code = 4;
}

message Criteria {
  repeated DialogueCriterion dialogue_criteria = 4;
}

message DialogueCriterion {
  string id = 1;
  string name = 2;
  string hypothesis = 3;
  int32 weight = 4;
}

message Address {
  string city = 1;
  string street = 2;
  string house = 3;
  string building = 4;
  string apartment = 5;
  optional int32 floor = 6;
}

message Person {
  string first_name = 1;
  string last_name = 2;
  string middle_name = 3;
  optional int32 age = 4;
  string phone = 5;
  string contact_phone = 6;
  string address = 7;
  string additional_info = 8;
  string on_scene_phone = 9;
}

enum ExecutionMode {
  EXECUTION_MODE_UNSPECIFIED = 0;
  EXECUTION_MODE_SEQUENTIAL = 1;
  EXECUTION_MODE_PARALLEL = 2;
}

enum IncidentTargetType {
  INCIDENT_TARGET_TYPE_UNSPECIFIED = 0;
  INCIDENT_TARGET_TYPE_SYSTEM_112 = 1;
  INCIDENT_TARGET_TYPE_DDS = 2;
}

enum Difficulty {
  DIFFICULTY_UNSPECIFIED = 0;
  DIFFICULTY_EASY = 1;
  DIFFICULTY_NORMAL = 2;
  DIFFICULTY_HARD = 3;
}

enum Gender {
  GENDER_UNSPECIFIED = 0;
  GENDER_MAN = 1;
  GENDER_WOMEN = 2;
}

enum IncidentStatus {
  INCIDENT_STATUS_UNSPECIFIED = 0;
  INCIDENT_STATUS_ADDED = 1;
  INCIDENT_STATUS_RECEIVED_BY_SERVICE = 2;
  INCIDENT_STATUS_ACCEPTED = 3;
  INCIDENT_STATUS_NOT_ACCEPTED = 4;
  INCIDENT_STATUS_RESPONSE_STARTED = 5;
  INCIDENT_STATUS_ARRIVED = 6;
  INCIDENT_STATUS_WORK_IN_PROGRESS = 7;
  INCIDENT_STATUS_WORK_COMPLETED = 8;
  INCIDENT_STATUS_WORK_REFUSED = 9;
  INCIDENT_STATUS_REGISTERED = 10;
  INCIDENT_STATUS_PROCESSED = 11;
  INCIDENT_STATUS_VERIFIED = 12;
  INCIDENT_STATUS_NOT_NOTIFIED = 13;
  INCIDENT_STATUS_REFUSED = 14;
  INCIDENT_STATUS_NOT_COMPLETED = 15;
  INCIDENT_STATUS_COMPLETED = 16;
}

enum DdsStageType {
  DDS_STAGE_TYPE_UNSPECIFIED = 0;
  DDS_STAGE_TYPE_ASSIGN_BRIGADE = 1;
  DDS_STAGE_TYPE_WAIT_FOR_BRIGADE_STATUS_CHANGE = 2;
  DDS_STAGE_TYPE_CALL_BRIGADE_FOR_STATUS = 3;
  DDS_STAGE_TYPE_REQUEST_ADDITIONAL_SERVICE = 4;
  DDS_STAGE_TYPE_COMPLETE_INCIDENT = 5;
}

enum CallDirection {
  CALL_DIRECTION_UNSPECIFIED = 0;
  CALL_DIRECTION_INBOUND = 1;
  CALL_DIRECTION_OUTBOUND = 2;
}

enum CounterpartyType {
  COUNTERPARTY_TYPE_UNSPECIFIED = 0;
  COUNTERPARTY_TYPE_CALLER = 1;
  COUNTERPARTY_TYPE_BRIGADE = 2;
  COUNTERPARTY_TYPE_SERVICE = 3;
}
