UPDATE incident_contexts
SET initial_assignment_service = CASE initial_assignment_service
    WHEN 'DDS_SERVICE_FIRE' THEN 'MCHS'
    WHEN 'DDS_SERVICE_GAS' THEN 'MOSGAZ'
    WHEN 'DDS_SERVICE_ANTI_TERROR' THEN 'FSB'
    WHEN 'DDS_SERVICE_POLICE' THEN 'POLICE'
    WHEN 'DDS_SERVICE_AMBULANCE' THEN 'AMBULANCE'
    WHEN 'FIRE' THEN 'MCHS'
    WHEN 'GAS' THEN 'MOSGAZ'
    WHEN 'ANTI_TERROR' THEN 'FSB'
    ELSE initial_assignment_service
END
WHERE initial_assignment_service IN ('DDS_SERVICE_FIRE', 'DDS_SERVICE_GAS', 'DDS_SERVICE_ANTI_TERROR', 'DDS_SERVICE_POLICE', 'DDS_SERVICE_AMBULANCE', 'FIRE', 'GAS', 'ANTI_TERROR');

UPDATE context_service_reactions
SET service_code = CASE service_code
    WHEN 'DDS_SERVICE_FIRE' THEN 'MCHS'
    WHEN 'DDS_SERVICE_GAS' THEN 'MOSGAZ'
    WHEN 'DDS_SERVICE_ANTI_TERROR' THEN 'FSB'
    WHEN 'DDS_SERVICE_POLICE' THEN 'POLICE'
    WHEN 'DDS_SERVICE_AMBULANCE' THEN 'AMBULANCE'
    WHEN 'FIRE' THEN 'MCHS'
    WHEN 'GAS' THEN 'MOSGAZ'
    WHEN 'ANTI_TERROR' THEN 'FSB'
    ELSE service_code
END
WHERE service_code IN ('DDS_SERVICE_FIRE', 'DDS_SERVICE_GAS', 'DDS_SERVICE_ANTI_TERROR', 'DDS_SERVICE_POLICE', 'DDS_SERVICE_AMBULANCE', 'FIRE', 'GAS', 'ANTI_TERROR');

UPDATE solution_context_services
SET service_code = CASE service_code
    WHEN 'FIRE' THEN 'MCHS'
    WHEN 'GAS' THEN 'MOSGAZ'
    WHEN 'ANTI_TERROR' THEN 'FSB'
    ELSE service_code
END
WHERE service_code IN ('FIRE', 'GAS', 'ANTI_TERROR');
