# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/simulator112/review/review_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'com/simulator112/review/review_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.grpc.com.simulator112.context import context_service_pb2 as com_dot_simulator112_dot_context_dot_context__service__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,com/simulator112/review/review_service.proto\x12\x13simulator112.review\x1a.com/simulator112/context/context_service.proto\"<\n\x13SendOnReviewRequest\x12%\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x14.context.FullContext\" \n\x10GetReviewRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"I\n\x14ReviewStatusResponse\x12\x31\n\x06status\x18\x01 \x01(\x0e\x32!.simulator112.review.ReviewStatus*L\n\x0cReviewStatus\x12\x0b\n\x07\x43REATED\x10\x00\x12\n\n\x06\x46ILLED\x10\x01\x12\r\n\tIN_REVIEW\x10\x02\x12\n\n\x06\x44IALOG\x10\x03\x12\x08\n\x04\x44ONE\x10\x04\x32\xd3\x01\n\rReviewService\x12\x63\n\x0csendOnReview\x12(.simulator112.review.SendOnReviewRequest\x1a).simulator112.review.ReviewStatusResponse\x12]\n\tgetReview\x12%.simulator112.review.GetReviewRequest\x1a).simulator112.review.ReviewStatusResponseB)\n%com.simulator112.review.grpc.contractP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.simulator112.review.review_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%com.simulator112.review.grpc.contractP\001'
  _globals['_REVIEWSTATUS']._serialized_start=288
  _globals['_REVIEWSTATUS']._serialized_end=364
  _globals['_SENDONREVIEWREQUEST']._serialized_start=117
  _globals['_SENDONREVIEWREQUEST']._serialized_end=177
  _globals['_GETREVIEWREQUEST']._serialized_start=179
  _globals['_GETREVIEWREQUEST']._serialized_end=211
  _globals['_REVIEWSTATUSRESPONSE']._serialized_start=213
  _globals['_REVIEWSTATUSRESPONSE']._serialized_end=286
  _globals['_REVIEWSERVICE']._serialized_start=367
  _globals['_REVIEWSERVICE']._serialized_end=578
# @@protoc_insertion_point(module_scope)
