# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc.com.simulator112.review import review_service_pb2 as com_dot_simulator112_dot_review_dot_review__service__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in com/simulator112/review/review_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReviewServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendOnReview = channel.unary_unary(
                '/simulator112.review.ReviewService/sendOnReview',
                request_serializer=com_dot_simulator112_dot_review_dot_review__service__pb2.SendOnReviewRequest.SerializeToString,
                response_deserializer=com_dot_simulator112_dot_review_dot_review__service__pb2.ReviewStatusResponse.FromString,
                _registered_method=True)
        self.getReview = channel.unary_unary(
                '/simulator112.review.ReviewService/getReview',
                request_serializer=com_dot_simulator112_dot_review_dot_review__service__pb2.GetReviewRequest.SerializeToString,
                response_deserializer=com_dot_simulator112_dot_review_dot_review__service__pb2.ReviewStatusResponse.FromString,
                _registered_method=True)


class ReviewServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def sendOnReview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getReview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReviewServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendOnReview': grpc.unary_unary_rpc_method_handler(
                    servicer.sendOnReview,
                    request_deserializer=com_dot_simulator112_dot_review_dot_review__service__pb2.SendOnReviewRequest.FromString,
                    response_serializer=com_dot_simulator112_dot_review_dot_review__service__pb2.ReviewStatusResponse.SerializeToString,
            ),
            'getReview': grpc.unary_unary_rpc_method_handler(
                    servicer.getReview,
                    request_deserializer=com_dot_simulator112_dot_review_dot_review__service__pb2.GetReviewRequest.FromString,
                    response_serializer=com_dot_simulator112_dot_review_dot_review__service__pb2.ReviewStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simulator112.review.ReviewService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('simulator112.review.ReviewService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReviewService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sendOnReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator112.review.ReviewService/sendOnReview',
            com_dot_simulator112_dot_review_dot_review__service__pb2.SendOnReviewRequest.SerializeToString,
            com_dot_simulator112_dot_review_dot_review__service__pb2.ReviewStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator112.review.ReviewService/getReview',
            com_dot_simulator112_dot_review_dot_review__service__pb2.GetReviewRequest.SerializeToString,
            com_dot_simulator112_dot_review_dot_review__service__pb2.ReviewStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
