from typing import Protocol

from app.application.model.session import DialogSession
from app.domain.model import CallScenario, DialogTranscript


class DialogUseCase(Protocol):
    def session(self, context_id: str) -> DialogSession: ...
    def next_call(self, context_id: str) -> CallScenario: ...
    def resume_call(self, context_id: str) -> CallScenario: ...
    def restart_call(self, context_id: str) -> CallScenario: ...
    def transcript_for_resume(self, context_id: str, call_id: str) -> DialogTranscript: ...
    def complete(self, context_id: str, call_id: str, transcript: DialogTranscript) -> None: ...
    def disconnect(self, context_id: str, call_id: str, transcript: DialogTranscript) -> None: ...
