server:
  port: 8085
spring:
  application:
    name: review-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/review}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  grpc:
    server:
      port: 9092
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
review:
  dialogue-analysis:
    base-url: ${MLSERVER_URL:http://localhost:8080}
    model-name: ${MLSERVER_MODEL_NAME:rubert-tiny-bilingual-nli}
    threshold: ${MLSERVER_ENTAILMENT_THRESHOLD:0.8}
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
