# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/simulator112/incident/incident_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'com/simulator112/incident/incident_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.grpc.com.simulator112.incident import incident_context_pb2 as com_dot_simulator112_dot_incident_dot_incident__context__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0com/simulator112/incident/incident_service.proto\x12\x08incident\x1a\x30\x63om/simulator112/incident/incident_context.proto\"-\n\x19GetIncidentContextRequest\x12\x10\n\x08level_id\x18\x01 \x01(\t2h\n\x13IncidentGrpcService\x12Q\n\x12GetIncidentContext\x12#.incident.GetIncidentContextRequest\x1a\x16.incident.LevelContextB+\n\'com.simulator112.incident.grpc.contractP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.simulator112.incident.incident_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\'com.simulator112.incident.grpc.contractP\001'
  _globals['_GETINCIDENTCONTEXTREQUEST']._serialized_start=112
  _globals['_GETINCIDENTCONTEXTREQUEST']._serialized_end=157
  _globals['_INCIDENTGRPCSERVICE']._serialized_start=159
  _globals['_INCIDENTGRPCSERVICE']._serialized_end=263
# @@protoc_insertion_point(module_scope)
