name: notification-service

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - backend/notification-service/**
      - .github/workflows/notification-service.yml

jobs:
  build-and-deploy:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_build-and-deploy-service.yml
    with:
      image: notification-service
      context: backend
      dockerfile: backend/notification-service/Dockerfile
      compose_service: notification-service
      image_env: NOTIFICATION_SERVICE_IMAGE
      container_suffix: notification
